quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/gbtp1
quarkus.datasource.username=bieltp1
quarkus.datasource.password=150326

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# Libera o acesso ao Swagger UI sem precisar de token
quarkus.http.auth.permission.public.paths=/q/swagger-ui*,/q/openapi*
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.public.methods=GET

# Desativa a criação automática do esquema de segurança OAuth2 (as caixinhas chatas)
quarkus.smallrye-openapi.auto-add-security=false

# Mantenha as configurações de banco de dados...
quarkus.http.port=8081

# Configuração OIDC (Keycloak)
quarkus.oidc.auth-server-url=http://localhost:8080/realms/meu-realm
quarkus.oidc.client-id=quarkuss
quarkus.oidc.credentials.secret=4sTLeqhWFGK8raI9YT2teXNBXB6GO7iO
quarkus.oidc.application-type=service

# IMPORTANTE: Diga ao Quarkus onde buscar as roles dentro do Token do Keycloak
quarkus.oidc.roles.role-claim-path=realm_access/roles
