@startuml

skinparam classAttributeIconSize 0

abstract class Pessoa   {
  -nome: String
  -email: String
}


class Cliente extends Pessoa {
  -dataCadastro: LocalDateTime
}
class Endereco   {
  -rua: String
  -cep: String
}
class Telefone   {
  -numero: String
  -ddd: String
}
class Funcionario extends Pessoa {
  -cargo: String
  -dataAdmissao: LocalDate
}
class Fornecedor extends Pessoa {
  -razaoSocial: String
  -cnpj: String
}
class Fonte   {
  -nome: String
  -potencia: Integer
  -preco: double
  -estoque: Integer
}
class Marca   {
  -nome: String
}
class Categoria   {
  -nome: String
}
enum Certificacao {
  + BRONZE 
  + SILVER
  + GOLD
}

Cliente "1" *-- "*" Endereco
Cliente "1" *-- "*" Telefone

Fonte "0..*" o-- "1" Marca
Fonte "*" -- "1" Categoria
Fonte "1" -- "1" Certificacao

@enduml