@startuml

skinparam classAttributeIconSize 0

abstract class Pessoa {
  -nome: String
  -email: String
}

class Cliente extends Pessoa {
  -dataCadastro: LocalDateTime
}
class Endereco {
  -rua: String
  -cep: String
}
class Telefone {
  -numero: String
  -ddd: String
}

Class Departamento {
  -sigla: String
  -descricao: String
}
enum StatusDepartamento {
  + ATIVO
  + INATIVO
}
class Funcionario extends Pessoa {
  -cargo: String
  -dataAdmissao: LocalDate
}
class Fornecedor extends Pessoa {
  -razaoSocial: String
  -cnpj: String
}
class Fonte {
  -nome: String
  -potencia: Integer
  -preco: double
  -estoque: Integer
}
class Marca {
  -nome: String
}
enum Certificacao {
  + BRONZE
  + SILVER
  + GOLD
}

Cliente "1" *-- "*" Endereco
Cliente "1" *-- "*" Telefone
Funcionario "0..*" -- "1" Departamento
Fonte "0..*" o-- "1" Marca
Fonte "1" -- "1" Certificacao

Departamento "1" o-right--- "1" StatusDepartamento


@enduml